### ISSUE TITLE
Symlink to bootstrap_cmds

### ISSUE THREAD

**Issue by thopiekar** [LubosD/darling-libsystem#1]
I just wanted to test the build process and found this:

```
thopiekar@home $ cmake .
CMake Error at CMakeLists.txt:7 (add_subdirectory):
  add_subdirectory given source "bootstrap_cmds" which is not an existing
  directory.


-- Building for x86_64, 
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Configuring incomplete, errors occurred!
See also "/home/thopiekar/Projekte/GIT/LubosD/darling-libsystem/CMakeFiles/CMakeOutput.log".
```
Would be great if you could add the missing content or make it independent from this directory if the content is unnecessary.

Thanks!

**Comment by thopiekar** [comment]
Oh, sorry, didn't take a look at the symlink closely.
It is just pointing to the absolute path except to the relative path.

- https://github.com/LubosD/darling-libsystem/blob/master/bootstrap_cmds

**Comment by LubosD** [comment]
Thank you, fixed!
